export const messages: Readonly<Record<string, string>> = {
  "nav.dashboard": "Dashboard",
  "nav.masterData": "Master data",
  "nav.transactions": "Transactions",
  "nav.income": "Income",
  "nav.csvImport": "CSV import",
  "nav.rules": "Categorization rules",
  "common.name": "Name",
  "common.owner": "Owner",
  "common.status": "Status",
  "common.actions": "Actions",
  "common.active": "Active",
  "common.edit": "Edit",
  "common.delete": "Delete",
  "common.account": "Account",
  "common.category": "Category",
  "common.date": "Date",
  "common.amount": "Amount",
  "common.description": "Description",
  "common.month": "Month",
  "common.note": "Note",
  "common.fixed": "fixed",
  "common.variable": "variable",
  "common.enabled": "active",
  "common.disabled": "inactive",
  "common.allAccounts": "All accounts",
  "common.allOwners": "All owners",
  "common.allCategories": "All categories",
  "common.unchanged": "leave unchanged",
  "seed.ownerContext.person_a": "Person A",
  "seed.ownerContext.person_b": "Person B",
  "seed.ownerContext.shared": "Shared",
  "seed.account.account-person-a-checking": "Person A checking account",
  "seed.account.account-person-b-checking": "Person B checking account",
  "seed.account.account-shared-checking": "Shared checking account",
  "seed.category.category-housing-rent": "Housing/rent",
  "seed.category.category-groceries": "Groceries",
  "seed.category.category-drugstore": "Drugstore",
  "seed.category.category-insurance": "Insurance",
  "seed.category.category-mobility": "Mobility",
  "seed.category.category-health": "Health",
  "seed.category.category-child-baby": "Child/baby",
  "seed.category.category-subscriptions": "Subscriptions",
  "seed.category.category-leisure": "Leisure",
  "seed.category.category-vacation": "Vacation",
  "seed.category.category-clothing": "Clothing",
  "seed.category.category-other": "Other",
  "auth.loginTitle": "FamilyFlow sign in",
  "auth.loginHeading": "Sign in",
  "auth.signIn": "Sign in as test user",
  "auth.dashboardTitle": "FamilyFlow dashboard",
  "auth.signedIn": "Signed in as",
  "auth.logout": "Sign out",
  "auth.errorTitle": "FamilyFlow error",
  "auth.errorHeading": "Authentication error",
  "auth.backToLogin": "Back to sign in",
  "auth.missingOidcConfig": "The OIDC configuration is missing.",
  "auth.notFound": "Not found",
  "auth.invalidCallback": "Invalid OIDC callback state.",
  "auth.invalidLogoutOrigin": "Invalid sign-out origin.",
  "auth.invalidSession": "Invalid session.",
  "auth.missingUserContext": "The signed-in user context is missing.",
  "error.badRequest": "Bad request",
  "error.notFoundHeading": "Page not found",
  "error.notFoundMessage": "The requested page was not found.",
  "error.unexpectedHeading": "Internal server error",
  "error.unexpectedMessage": "An unexpected error occurred.",
  "error.requestId": "Request ID:",
  "error.requestFailed": "The request could not be processed.",
  "missing.account.heading": "Account not found",
  "missing.account.message": "The requested account was not found.",
  "missing.category.heading": "Category not found",
  "missing.category.message": "The requested category was not found.",
  "missing.categorizationRule.heading": "Categorization rule not found",
  "missing.categorizationRule.message": "The requested categorization rule was not found.",
  "missing.incomePlan.heading": "Income not found",
  "missing.incomePlan.message": "The requested income was not found.",
  "missing.transaction.heading": "Transaction not found",
  "missing.transaction.message": "The requested transaction was not found.",
  "transaction.title": "FamilyFlow transactions",
  "transaction.heading": "Transactions",
  "transaction.add": "Add transaction",
  "transaction.edit": "Edit transaction",
  "transaction.save": "Save transaction",
  "transaction.payee": "Payee",
  "transaction.purpose": "Purpose",
  "transaction.fixedCosts": "Fixed costs",
  "transaction.filters": "Filters",
  "transaction.filterAccount": "Filter account",
  "transaction.filterCategory": "Filter category",
  "transaction.filterOwner": "Owner",
  "transaction.filterStatus": "Filter status",
  "transaction.costType": "Cost type",
  "transaction.transferStatus": "Transfer status",
  "transaction.applyFilters": "Apply filters",
  "transaction.list": "Transactions list",
  "transaction.empty": "No transactions found.",
  "transaction.booked": "booked",
  "transaction.planned": "planned",
  "transaction.internalTransfer": "Internal transfer",
  "transaction.markTransfer": "Mark as transfer",
  "transaction.unmarkTransfer": "Unmark transfer",
  "transaction.marked": "marked",
  "transaction.unmarked": "unmarked",
  "transaction.allStatuses": "All statuses",
  "transaction.allCosts": "All costs",
  "transaction.allTransactions": "All transactions",
  "transaction.datePlaceholder": "MM/DD/YYYY",
  "transaction.amountPlaceholder": "1,234.56",
  "transaction.monthPlaceholder": "MM/YYYY",
  "transaction.saveFailed": "The transaction could not be saved.",
  "transaction.invalidTransferStatus": "The transfer status must be exactly true or false.",
  "income.title": "FamilyFlow income",
  "income.heading": "Income",
  "income.add": "Add income",
  "income.edit": "Edit income",
  "income.save": "Save income",
  "income.label": "Description",
  "income.startMonth": "Start month",
  "income.endMonth": "End month",
  "income.overrideHeading": "Monthly override",
  "income.overrideIncome": "Income",
  "income.overrideAmount": "Override amount",
  "income.overrideNote": "Override note",
  "income.saveOverride": "Save override",
  "income.filters": "Income filters",
  "income.calculationMonth": "Calculation month",
  "income.filterOwner": "Filter owner",
  "income.applyFilters": "Filter income",
  "income.updateCalculation": "Update calculation",
  "income.summary": "Monthly income summary",
  "income.list": "Income list",
  "income.empty": "No income found.",
  "income.overrides": "Monthly overrides",
  "income.noOverrides": "No monthly overrides found.",
  "income.start": "Start",
  "income.end": "End",
  "income.monthlyTotal": "Planned monthly income: {amount}",
  "income.saveFailed": "The income could not be saved.",
  "income.overrideSaveFailed": "The override could not be saved.",
  "master.title": "FamilyFlow master data",
  "master.accounts": "Accounts",
  "master.categories": "Categories",
  "master.newAccountName": "New account name",
  "master.accountOwner": "Account owner",
  "master.addAccount": "Add account",
  "master.editAccount": "Edit account",
  "master.deactivateAccount": "Deactivate account",
  "master.ownerContexts": "Account owners",
  "master.ownerKey": "Owner key",
  "master.displayName": "Display name",
  "master.newCategoryName": "New category name",
  "master.addCategory": "Add category",
  "master.editCategory": "Edit category",
  "master.deactivateCategory": "Deactivate category",
  "master.accountName": "Account name",
  "master.saveAccount": "Save account",
  "master.categoryName": "Category name",
  "master.saveCategory": "Save category",
  "master.ownerInput": "Owner name for {owner}",
  "master.ownerSave": "Save owner name for {owner}",
  "master.saveFailed": "The master data could not be saved.",
  "rules.title": "FamilyFlow categorization rules",
  "rules.heading": "Categorization rules",
  "rules.add": "Add categorization rule",
  "rules.edit": "Edit categorization rule",
  "rules.save": "Save rule",
  "rules.addSubmit": "Add rule",
  "rules.ruleName": "Rule name",
  "rules.searchText": "Search text",
  "rules.fixedAction": "Fixed-cost action",
  "rules.transferAction": "Transfer action",
  "rules.priority": "Priority",
  "rules.list": "Rule list",
  "rules.apply": "Apply rules to existing transactions",
  "rules.applyResult": "{changed} changed, {unchanged} unchanged",
  "rules.empty": "No categorization rules found.",
  "rules.fixedColumn": "Fixed costs",
  "rules.transferColumn": "Internal transfer",
  "rules.markFixed": "mark fixed",
  "rules.markVariable": "mark variable",
  "rules.markTransfer": "mark transfer",
  "rules.unmarkTransfer": "unmark transfer",
  "rules.saveFailed": "The categorization rule could not be saved.",
  "csv.title": "CSV import",
  "csv.upload": "Upload CSV",
  "csv.profileSaved": "Import profile saved.",
  "csv.profile": "Import profile",
  "csv.loadProfile": "Load import profile",
  "csv.profileName": "Profile name",
  "csv.account": "Import account",
  "csv.delimiter": "CSV delimiter",
  "csv.encoding": "CSV character encoding",
  "csv.dateFormat": "CSV date format",
  "csv.decimalFormat": "CSV decimal format",
  "csv.dateColumn": "Date column",
  "csv.amountColumn": "Amount column",
  "csv.descriptionColumn": "Description column",
  "csv.payeeColumn": "Payee column",
  "csv.purposeColumn": "Purpose column",
  "csv.categoryColumn": "Category column",
  "csv.file": "CSV file",
  "csv.preview": "Show import preview",
  "csv.saveProfile": "Save import profile",
  "csv.previewHeading": "Import preview",
  "csv.noRows": "No CSV rows found.",
  "csv.line": "Line",
  "csv.outcome": "Outcome",
  "csv.reason": "Reason",
  "csv.confirm": "Confirm import",
  "csv.manual": "Manual mapping",
  "csv.semicolon": "Semicolon",
  "csv.comma": "Comma",
  "csv.tab": "Tab",
  "csv.decimalComma": "Decimal comma",
  "csv.decimalPoint": "Decimal point",
  "csv.importable": "importable",
  "csv.duplicate": "duplicate",
  "csv.ignored": "ignored",
  "csv.invalid": "invalid",
  "csv.alreadyImported": "already imported",
  "csv.new": "new",
  "csv.profileSaveFailed": "The import profile could not be saved.",
  "csv.previewFailed": "The CSV import preview failed.",
};
