export const messages: Record<string, string> = {
  "nav.dashboard": "Übersicht",
  "nav.masterData": "Stammdaten",
  "nav.transactions": "Transaktionen",
  "nav.income": "Einnahmen",
  "nav.csvImport": "CSV-Import",
  "nav.rules": "Kategorisierungsregeln",
  "common.name": "Name",
  "common.owner": "Eigentümer",
  "common.status": "Status",
  "common.actions": "Aktionen",
  "common.active": "Aktiv",
  "common.edit": "Bearbeiten",
  "common.delete": "Löschen",
  "common.account": "Konto",
  "common.category": "Kategorie",
  "common.date": "Datum",
  "common.amount": "Betrag",
  "common.description": "Beschreibung",
  "common.month": "Monat",
  "common.note": "Notiz",
  "common.fixed": "fix",
  "common.variable": "variabel",
  "common.enabled": "aktiv",
  "common.disabled": "inaktiv",
  "common.allAccounts": "Alle Konten",
  "common.allOwners": "Alle Eigentümer",
  "common.allCategories": "Alle Kategorien",
  "common.unchanged": "unverändert lassen",
  "seed.ownerContext.person_a": "Person A",
  "seed.ownerContext.person_b": "Person B",
  "seed.ownerContext.shared": "Gemeinsam",
  "seed.account.account-person-a-checking": "Girokonto Person A",
  "seed.account.account-person-b-checking": "Girokonto Person B",
  "seed.account.account-shared-checking": "Gemeinsames Girokonto",
  "seed.category.category-housing-rent": "Wohnen/Miete",
  "seed.category.category-groceries": "Lebensmittel",
  "seed.category.category-drugstore": "Drogerie",
  "seed.category.category-insurance": "Versicherungen",
  "seed.category.category-mobility": "Mobilität",
  "seed.category.category-health": "Gesundheit",
  "seed.category.category-child-baby": "Kind/Baby",
  "seed.category.category-subscriptions": "Abos",
  "seed.category.category-leisure": "Freizeit",
  "seed.category.category-vacation": "Urlaub",
  "seed.category.category-clothing": "Kleidung",
  "seed.category.category-other": "Sonstiges",
  "auth.loginTitle": "FamilyFlow Anmeldung",
  "auth.loginHeading": "Anmeldung",
  "auth.signIn": "Als Testbenutzer anmelden",
  "auth.dashboardTitle": "FamilyFlow Übersicht",
  "auth.signedIn": "Angemeldet als",
  "auth.logout": "Abmelden",
  "auth.errorTitle": "FamilyFlow Fehler",
  "auth.errorHeading": "Authentifizierungsfehler",
  "auth.backToLogin": "Zurück zur Anmeldung",
  "auth.missingOidcConfig": "Die OIDC-Konfiguration fehlt.",
  "auth.notFound": "Nicht gefunden",
  "auth.invalidCallback": "Ungültiger OIDC-Rückrufstatus.",
  "auth.invalidLogoutOrigin": "Ungültiger Ursprung für die Abmeldung.",
  "auth.invalidSession": "Ungültige Sitzung.",
  "auth.missingUserContext": "Der angemeldete Benutzerkontext fehlt.",
  "dashboard.title": "FamilyFlow Übersicht",
  "dashboard.heading": "Monatliche Übersicht",
  "dashboard.filters": "Dashboard filters",
  "dashboard.apply": "Filter anwenden",
  "dashboard.income": "Geplante Einnahmen",
  "dashboard.expenses": "Gebuchte Ausgaben",
  "dashboard.balance": "Saldo",
  "dashboard.averages": "Historische Ausgabendurchschnitte (Monate)",
  "dashboard.byCategory": "Ausgaben nach Kategorie",
  "dashboard.byAccount": "Ausgaben nach Konto",
  "dashboard.forecast": "Monatsprognose",
  "dashboard.noForecast": "Für vergangene Monate wird keine Prognose angezeigt.",
  "dashboard.bookedFixed": "Gebuchte Fixkosten",
  "dashboard.plannedFixed": "Offene geplante Fixkosten",
  "dashboard.variableForecast": "Hochgerechnete variable Ausgaben",
  "dashboard.forecastTotal": "Prognosesumme",
  "dashboard.futureMonth": "Zukünftige Monate können nicht ausgewählt werden.",
  "error.badRequest": "Ungültige Anfrage",
  "error.notFoundHeading": "Seite nicht gefunden",
  "error.notFoundMessage": "Die angeforderte Seite wurde nicht gefunden.",
  "error.unexpectedHeading": "Interner Serverfehler",
  "error.unexpectedMessage": "Ein unerwarteter Fehler ist aufgetreten.",
  "error.requestId": "Anfrage-ID:",
  "error.requestFailed": "Die Anfrage konnte nicht verarbeitet werden.",
  "missing.account.heading": "Konto nicht gefunden",
  "missing.account.message": "Das angeforderte Konto wurde nicht gefunden.",
  "missing.category.heading": "Kategorie nicht gefunden",
  "missing.category.message": "Die angeforderte Kategorie wurde nicht gefunden.",
  "missing.categorizationRule.heading": "Kategorisierungsregel nicht gefunden",
  "missing.categorizationRule.message":
    "Die angeforderte Kategorisierungsregel wurde nicht gefunden.",
  "missing.incomePlan.heading": "Einnahme nicht gefunden",
  "missing.incomePlan.message": "Die angeforderte Einnahme wurde nicht gefunden.",
  "missing.transaction.heading": "Transaktion nicht gefunden",
  "missing.transaction.message": "Die angeforderte Transaktion wurde nicht gefunden.",
  "transaction.title": "FamilyFlow Transaktionen",
  "transaction.heading": "Transaktionen",
  "transaction.add": "Transaktion hinzufügen",
  "transaction.edit": "Transaktion bearbeiten",
  "transaction.save": "Transaktion speichern",
  "transaction.payee": "Zahlungsempfänger",
  "transaction.purpose": "Verwendungszweck",
  "transaction.fixedCosts": "Fixkosten",
  "transaction.filters": "Filter",
  "transaction.filterAccount": "Konto filtern",
  "transaction.filterCategory": "Kategorie filtern",
  "transaction.filterOwner": "Eigentümer",
  "transaction.filterStatus": "Status filtern",
  "transaction.costType": "Kostenart",
  "transaction.transferStatus": "Umbuchungsstatus",
  "transaction.applyFilters": "Filter anwenden",
  "transaction.list": "Transaktionsliste",
  "transaction.empty": "Keine Transaktionen gefunden.",
  "transaction.booked": "gebucht",
  "transaction.planned": "geplant",
  "transaction.internalTransfer": "Interne Umbuchung",
  "transaction.markTransfer": "Als Umbuchung markieren",
  "transaction.unmarkTransfer": "Umbuchung aufheben",
  "transaction.marked": "markiert",
  "transaction.unmarked": "nicht markiert",
  "transaction.allStatuses": "Alle Status",
  "transaction.allCosts": "Alle Kosten",
  "transaction.allTransactions": "Alle Transaktionen",
  "transaction.datePlaceholder": "TT.MM.JJJJ",
  "transaction.amountPlaceholder": "1.234,56",
  "transaction.monthPlaceholder": "MM.JJJJ",
  "transaction.saveFailed": "Die Transaktion konnte nicht gespeichert werden.",
  "transaction.invalidTransferStatus": 'Der Umbuchungsstatus muss genau "true" oder "false" sein.',
  "income.title": "FamilyFlow Einnahmen",
  "income.heading": "Einnahmen",
  "income.add": "Einnahme hinzufügen",
  "income.edit": "Einnahme bearbeiten",
  "income.save": "Einnahme speichern",
  "income.activate": "Aktivieren",
  "income.deactivate": "Deaktivieren",
  "income.label": "Bezeichnung",
  "income.startMonth": "Startmonat",
  "income.endMonth": "Endmonat",
  "income.overrideHeading": "Monatliche Abweichung",
  "income.overrideIncome": "Einnahme",
  "income.overrideAmount": "Abweichender Betrag",
  "income.overrideNote": "Notiz zur Abweichung",
  "income.saveOverride": "Abweichung speichern",
  "income.filters": "Einnahmenfilter",
  "income.calculationMonth": "Berechnungsmonat",
  "income.filterOwner": "Eigentümer filtern",
  "income.applyFilters": "Einnahmen filtern",
  "income.updateCalculation": "Berechnung aktualisieren",
  "income.summary": "Monatliche Einnahmenübersicht",
  "income.list": "Einnahmenliste",
  "income.empty": "Keine Einnahmen gefunden.",
  "income.overrides": "Monatliche Abweichungen",
  "income.noOverrides": "Keine monatlichen Abweichungen gefunden.",
  "income.start": "Start",
  "income.end": "Ende",
  "income.monthlyTotal": "Geplante Monatseinnahmen: {amount}",
  "income.saveFailed": "Die Einnahme konnte nicht gespeichert werden.",
  "income.overrideSaveFailed": "Die Abweichung konnte nicht gespeichert werden.",
  "master.title": "FamilyFlow Stammdaten",
  "master.accounts": "Konten",
  "master.categories": "Kategorien",
  "master.newAccountName": "Neuer Kontoname",
  "master.accountOwner": "Kontoeigentümer",
  "master.addAccount": "Konto hinzufügen",
  "master.editAccount": "Konto bearbeiten",
  "master.deactivateAccount": "Konto deaktivieren",
  "master.ownerContexts": "Kontoeigentümer",
  "master.ownerKey": "Eigentümerschlüssel",
  "master.displayName": "Anzeigename",
  "master.newCategoryName": "Neuer Kategoriename",
  "master.addCategory": "Kategorie hinzufügen",
  "master.editCategory": "Kategorie bearbeiten",
  "master.deactivateCategory": "Kategorie deaktivieren",
  "master.accountName": "Kontoname",
  "master.saveAccount": "Konto speichern",
  "master.categoryName": "Kategoriename",
  "master.saveCategory": "Kategorie speichern",
  "master.ownerInput": "Eigentümername für {owner}",
  "master.ownerSave": "Eigentümername für {owner} speichern",
  "master.saveFailed": "Die Stammdaten konnten nicht gespeichert werden.",
  "rules.title": "FamilyFlow Kategorisierungsregeln",
  "rules.heading": "Kategorisierungsregeln",
  "rules.add": "Kategorisierungsregel hinzufügen",
  "rules.edit": "Kategorisierungsregel bearbeiten",
  "rules.save": "Regel speichern",
  "rules.addSubmit": "Regel hinzufügen",
  "rules.ruleName": "Regelname",
  "rules.searchText": "Suchtext",
  "rules.fixedAction": "Fixkostenaktion",
  "rules.transferAction": "Umbuchungsaktion",
  "rules.priority": "Priorität",
  "rules.list": "Regelliste",
  "rules.apply": "Regeln auf bestehende Transaktionen anwenden",
  "rules.applyResult": "{changed} geändert, {unchanged} unverändert",
  "rules.empty": "Keine Kategorisierungsregeln gefunden.",
  "rules.fixedColumn": "Fixkosten",
  "rules.transferColumn": "Interne Umbuchung",
  "rules.markFixed": "als fix markieren",
  "rules.markVariable": "als variabel markieren",
  "rules.markTransfer": "Umbuchung markieren",
  "rules.unmarkTransfer": "Umbuchung aufheben",
  "rules.saveFailed": "Die Kategorisierungsregel konnte nicht gespeichert werden.",
  "csv.title": "CSV-Import",
  "csv.upload": "CSV hochladen",
  "csv.profileSaved": "Importprofil gespeichert.",
  "csv.profile": "Importprofil",
  "csv.loadProfile": "Importprofil laden",
  "csv.profileName": "Profilname",
  "csv.account": "Importkonto",
  "csv.delimiter": "CSV-Trennzeichen",
  "csv.encoding": "CSV-Zeichenkodierung",
  "csv.dateFormat": "CSV-Datumsformat",
  "csv.decimalFormat": "CSV-Dezimalformat",
  "csv.dateColumn": "Datumsspalte",
  "csv.amountColumn": "Betragsspalte",
  "csv.descriptionColumn": "Beschreibungsspalte",
  "csv.payeeColumn": "Zahlungsempfängerspalte",
  "csv.purposeColumn": "Verwendungszweckspalte",
  "csv.categoryColumn": "Kategoriespalte",
  "csv.file": "CSV-Datei",
  "csv.preview": "Importvorschau anzeigen",
  "csv.saveProfile": "Importprofil speichern",
  "csv.previewHeading": "Importvorschau",
  "csv.noRows": "Keine CSV-Zeilen gefunden.",
  "csv.line": "Zeile",
  "csv.outcome": "Ergebnis",
  "csv.reason": "Grund",
  "csv.confirm": "Import bestätigen",
  "csv.manual": "Manuelle Zuordnung",
  "csv.semicolon": "Semikolon",
  "csv.comma": "Komma",
  "csv.tab": "Tab",
  "csv.decimalComma": "Dezimalkomma",
  "csv.decimalPoint": "Dezimalpunkt",
  "csv.importable": "importierbar",
  "csv.duplicate": "Duplikat",
  "csv.ignored": "ignoriert",
  "csv.invalid": "ungültig",
  "csv.alreadyImported": "bereits importiert",
  "csv.new": "neu",
  "csv.profileSaveFailed": "Das Importprofil konnte nicht gespeichert werden.",
  "csv.previewFailed": "Die CSV-Importvorschau ist fehlgeschlagen.",
  "nav.scenarios": "Szenarien",
  "nav.calculators": "Rechner und Hilfen",
  "scenario.title": "FamilyFlow Szenarien",
  "scenario.heading": "Familienfinanzszenarien",
  "scenario.create": "Szenario anlegen",
  "scenario.name": "Bezeichnung",
  "scenario.startMonth": "Startmonat",
  "scenario.endMonth": "Endmonat",
  "scenario.startingBuffer": "Startpuffer",
  "scenario.baseIncome": "Monatliche Einnahmen",
  "scenario.baseline": "Ausgabenbasis",
  "scenario.baselineChoice": "Berechnungsgrundlage",
  "scenario.manualBaseline": "Manueller Betrag",
  "scenario.historical3": "Historischer Durchschnitt (3 Monate)",
  "scenario.historical6": "Historischer Durchschnitt (6 Monate)",
  "scenario.historical12": "Historischer Durchschnitt (12 Monate)",
  "scenario.save": "Szenario speichern",
  "scenario.edit": "Szenario bearbeiten",
  "scenario.update": "Änderungen speichern",
  "scenario.preserveBaseline": "Bestehende Grundlage beibehalten",
  "scenario.adjustment": "Anpassung",
  "scenario.type": "Art",
  "scenario.income": "Einnahmen",
  "scenario.expense": "Ausgaben",
  "scenario.direction": "Änderung",
  "scenario.increase": "Erhöhung",
  "scenario.decrease": "Verringerung",
  "scenario.from": "Von Monat",
  "scenario.to": "Bis Monat",
  "scenario.add": "Anpassung hinzufügen",
  "scenario.lowestBuffer": "Niedrigster Puffer",
  "scenario.requiredIncome": "Zusätzlich benötigtes Nettoeinkommen",
  "scenario.balance": "Saldo",
  "scenario.buffer": "Puffer",
  "scenario.empty": "Noch kein Szenario vorhanden.",
  "scenario.list": "Gespeicherte Szenarien",
  "scenario.baselineValue": "Ausgabenbasis: {amount}",
  "scenario.saveFailed": "Das Szenario konnte nicht gespeichert werden.",
  "calculator.title": "FamilyFlow Rechner und Hilfen",
  "calculator.heading": "Rechner und Hilfen",
  "calculator.intro": "Externe Rechner zur manuellen Planung:",
  "calculator.parental": "Elterngeldrechner des Familienportals",
  "calculator.tax": "Steuerrechner des Bundesministeriums der Finanzen",
};
